# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9f41f3ca7237fdbf048f06d8ad7fca50d6acc6a7d68ab33741b8a2281a51fd22e57d1499c4d0401860da7e0da8af909a551c9188e6d6292bcf94ea6643959a2

test:
  secret_key_base: 06d15c0b1f3919a975ba3200e719f41e27a3d064d18499a3327717d5f8fde59e1a80726f8252edb850d03f40bd4a5d3ddc0ab81042ec1d6c3a40e661adc0c069

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
